
name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello. Thanks for submitting an issue about the Node-Red Contesting Dashboard. Please give the team some time to triage and reply with a more detailed response. \n 73, \n Connor KD9LSV"
        pr-message: "Thank you for submitting a pull request. A notification has been sent to the team to review your work and see if it is adaquate for us to merge into the project. If we have any questions, we will reach out. Please be patience with the status of the PR.\n 73,\n Connor KD9LSV"

